from __future__ import annotations

import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import List

from sqlalchemy.orm import Session

from ..config import settings
from ..database import EvidenceRecord, ReportRecordModel
from ..schemas import EvidenceChunk, ReportRecord
from .fbs_pm_service import FBSPMService
from .gap_detection_service import GapDetectionService
from .ids import new_id
from .object_storage_service import ObjectStorageService
from .rag_service import RAGService
from .serialization import model_to_dict


class ReportService:
    def generate(self, db: Session, gap_id: str) -> ReportRecord:
        gap = GapDetectionService().get(db, gap_id)
        pathways = FBSPMService().list_for_gap(db, gap_id)
        evidence = RAGService().retrieve_boundary_evidence(db, gap_id, top_k=50)
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        report_id = new_id("report")
        md_path = settings.output_dir / f"report_{gap_id}_{timestamp}.md"
        json_path = settings.output_dir / f"result_{gap_id}_{timestamp}.json"
        csv_path = settings.output_dir / f"evidence_{gap_id}_{timestamp}.csv"
        settings.output_dir.mkdir(parents=True, exist_ok=True)

        md_path.write_text(self._markdown(gap, pathways, evidence), encoding="utf-8")
        json_path.write_text(
            json.dumps(
                {
                    "gap": model_to_dict(gap),
                    "pathways": [model_to_dict(pathway) for pathway in pathways],
                    "evidence": [model_to_dict(chunk) for chunk in evidence],
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        with csv_path.open("w", encoding="utf-8", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow(["evidence_id", "title", "authors", "year", "doi", "page", "section", "relevance_score", "snippet"])
            for chunk in evidence:
                writer.writerow(
                    [
                        chunk.evidence_id,
                        chunk.title,
                        "; ".join(chunk.authors),
                        chunk.year,
                        chunk.doi,
                        chunk.page,
                        chunk.section,
                        chunk.relevance_score,
                        chunk.snippet,
                    ]
                )
        object_storage = ObjectStorageService()
        markdown_ref = object_storage.upload_file(md_path, f"reports/{report_id}/{md_path.name}", content_type="text/markdown")
        json_ref = object_storage.upload_file(json_path, f"reports/{report_id}/{json_path.name}", content_type="application/json")
        csv_ref = object_storage.upload_file(csv_path, f"reports/{report_id}/{csv_path.name}", content_type="text/csv")
        record = ReportRecord(
            report_id=report_id,
            gap_id=gap_id,
            markdown_path=markdown_ref,
            json_path=json_ref,
            evidence_csv_path=csv_ref,
            created_at=datetime.now(timezone.utc).isoformat(),
        )
        db.add(ReportRecordModel(report_id=report_id, gap_id=gap_id, payload=model_to_dict(record)))
        db.commit()
        return record

    def list(self, db: Session) -> List[ReportRecord]:
        return [ReportRecord(**record.payload) for record in db.query(ReportRecordModel).order_by(ReportRecordModel.created_at.desc())]

    def _markdown(self, gap, pathways, evidence: List[EvidenceChunk]) -> str:
        lines = [
            f"# Application Finder Report: {gap.title}",
            "",
            "Generated by Application Finder",
            "",
            "## Scope",
            gap.scope_id,
            "",
            "## Gap Summary",
            gap.explanation,
            "",
            "## Scores",
            f"- Novelty: {gap.novelty_score}",
            f"- Feasibility: {gap.feasibility_score}",
            f"- Boundary evidence: {gap.boundary_evidence_score}",
            f"- Uncertainty: {gap.uncertainty_score}",
            "",
            "## Missing Descriptor Combination",
            "```json",
            json.dumps(gap.missing_descriptor_combination, indent=2),
            "```",
            "",
            "## Pseudo-Applications",
        ]
        lines.extend(f"- {item}" for item in gap.pseudo_application_hypotheses)
        lines.extend(["", "## FBS-PM Pathways"])
        for pathway in pathways:
            lines.extend(
                [
                    f"### {pathway.title}",
                    f"- Function: {pathway.function}",
                    f"- Behaviour / EM mechanism: {pathway.behaviour_or_mechanism}",
                    f"- Structure / device route: {pathway.structure_or_device_realization}",
                    f"- Validation status: {pathway.validation_status}",
                    f"- Uncertainty: {pathway.uncertainty}",
                ]
            )
        lines.extend(["", "## Evidence Table"])
        for chunk in evidence[:25]:
            lines.append(f"- {chunk.title} ({chunk.year or 'n.d.'}) `{chunk.evidence_id}`: {chunk.snippet[:240]}")
        lines.extend(
            [
                "",
                "## Limitations",
                "Generated pathways and MatterGen outputs require independent property validation before scientific claims are made.",
            ]
        )
        return "\n".join(lines) + "\n"
